name: Pipeline CloudSim

on:
  workflow_dispatch:

jobs:
  simulation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4
      
      - name: Installation Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Permissions scripts
        run: |
          chmod +x build.sh
          chmod +x run-simulation.sh
      
      - name: Compilation
        run: ./build.sh
      
      - name: Execution
        run: ./run-simulation.sh
      
      - name: Sauvegarde resultats
        uses: actions/upload-artifact@v4
        with:
          name: simulation-results-${{ github.run_id }}
          path: results/
          retention-days: 30